"""empty message

Revision ID: 47d8ce5519d2
Revises: ed0dcb443322
Create Date: 2025-04-28 20:12:07.965344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # 추가


# revision identifiers, used by Alembic.
revision: str = '47d8ce5519d2'
down_revision: Union[str, None] = 'ed0dcb443322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
