"""empty message

Revision ID: 8103ac703e67
Revises: ed22a874fa90
Create Date: 2025-04-28 18:44:11.218685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # 추가


# revision identifiers, used by Alembic.
revision: str = '8103ac703e67'
down_revision: Union[str, None] = 'ed22a874fa90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
