"""empty message

Revision ID: e1d377297cbe
Revises: 9f95a1fa68b7
Create Date: 2025-04-28 17:37:11.704991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # 추가


# revision identifiers, used by Alembic.
revision: str = 'e1d377297cbe'
down_revision: Union[str, None] = '9f95a1fa68b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
